export type Cadre = {
    id: number;
    position: number;
    ruche_id: number;
    created_at?: string;
    updated_at?: string;
    type_cadres?: TypeCadre[];
};
export type Comptage = {
    id: number;
    visite_id: number;
    suit_traitement: boolean;
    type: string;
    nb_varroas?: number;
    duree?: number;
    poids_abeilles?: number;
    produits_traitement_id?: number;
    nb_abeilles?: number;
    created_at?: string;
    updated_at?: string;
    visite?: Visite;
    produits_traitement?: ProduitTraitement;
};
export type Controle = {
    id: number;
    visite_id: number;
    comportement: number;
    force: number;
    reserves?: number;
    reine_vue: boolean;
    debut_de_ponte: boolean;
    essaimee: boolean;
    males: number;
    reine_morte: boolean;
    couvain_platre: boolean;
    loque_americaine: boolean;
    loque_europeenne: boolean;
    nosemose: boolean;
    maladie_noire: boolean;
    autre_virus: string;
    frelon_europeen: boolean;
    frelon_asiatique: boolean;
    frelon_oriental: boolean;
    varroas: boolean;
    fausse_teigne: boolean;
    aethina_tumida: boolean;
    created_at?: string;
    updated_at?: string;
    visite?: Visite;
};
export type Division = {
    id: number;
    visite_id: number;
    nb_cadres_pris: number;
    ruche_destination_id?: number;
    commentaires?: string;
    reine_prise: boolean;
    created_at?: string;
    updated_at?: string;
    visite?: Visite;
    ruche_destination?: Ruche;
};
export type Exploitation = {
    id: number;
    nom: string;
    adresse1?: string;
    adresse2?: string;
    code_postal?: string;
    ville?: string;
    pays?: string;
    numero_bio?: string;
    siren?: string;
    proprietaire_id: number;
    created_at?: string;
    updated_at?: string;
    apiculteurs?: User[];
    roles?: Role[];
    visites?: Visite[];
    ruchers?: Rucher[];
    ruches?: Ruche[];
    ruches_archivees?: Ruche[];
    ruches_non_archivees?: Ruche[];
    partenaires?: Partenaire[];
    sirops?: Sirop[];
    proprietaire?: User;
    hausses?: Hausse[];
    hausses_recoltees?: HausseRecoltee[];
    hausses_a_extraire?: HausseRecoltee[];
    cadres?: Cadre[];
    types_ruches?: TypeRuche[];
};
export type ExploitationUserRole = {
    id: number;
    exploitation_id: number;
    user_id: number;
    role_id: number;
    created_at?: string;
    updated_at?: string;
    user?: User;
    exploitation?: Exploitation;
    role?: Role;
};
export type Extraction = {
    id: number;
    date: string;
    auteur_id: number;
    miellee_id: number;
    exploitation_id: number;
    created_at?: string;
    updated_at?: string;
    auteur?: User;
    miellee?: Miellee;
    hausses_recoltees?: HausseRecoltee[];
};
export type Hausse = {
    id: number;
    reference: string;
    taux_remplissage: number;
    ruche_id?: number;
    exploitation_id: number;
    created_at?: string;
    updated_at?: string;
    ruche?: Ruche;
    exploitation?: Exploitation;
    hausse_recoltees?: HausseRecoltee[];
    poses_hausses?: PoseHausses[];
};
export type HausseRecoltee = {
    id: number;
    recoltes_miel_id: number;
    hausse_id: number;
    ruche_id: number;
    extraction_id?: number;
    exploitation_id: number;
    qte_miel_recolte: number;
    taux_remplissage: number;
    created_at?: string;
    updated_at?: string;
    recoltes_miel?: RecolteMiel;
    hausse?: Hausse;
    ruche?: Ruche;
    exploitation?: Exploitation;
    extraction?: Extraction;
};
export type Introduction = {
    id: number;
    visite_id: number;
    reine_id?: number;
    souche_id?: number;
    mere_id?: number;
    generation?: string;
    type: string;
    age_cellule?: number;
    date_introduction: string;
    date_ctrl_naissance?: string;
    date_ctrl_ponte?: string;
    echec: boolean;
    terminee: boolean;
    commentaires?: string;
    created_at?: string;
    updated_at?: string;
    visite?: Visite;
    reine?: Reine;
    souche?: Souche;
    mere?: Reine;
    ruche?: Ruche;
};
export type Miellee = {
    id: number;
    nom: string;
    exploitation_id: number;
    created_at?: string;
    updated_at?: string;
    exploitation?: Exploitation;
};
export type Mort = {
    id: number;
    visite_id: number;
    commentaires?: string;
    created_at?: string;
    updated_at?: string;
    visite?: Visite;
};
export type NettoyagePlancher = {
    id: number;
    visite_id: number;
    niveau_proprete: number;
    presence_mycoses: boolean;
    presence_rongeurs: boolean;
    commentaires?: string;
    created_at?: string;
    updated_at?: string;
    visite?: Visite;
};
export type Note = {
    id: number;
    ruche_id?: number;
    rucher_id?: number;
    exploitation_id?: number;
    titre: string;
    contenu: string;
    created_at?: string;
    updated_at?: string;
    ruche?: Ruche;
    rucher?: Rucher;
};
export type Nourrissement = {
    id: number;
    qte_sirop: number;
    qte_candi: number;
    qte_miel: number;
    qte_pate_proteinee: number;
    visite_id: number;
    sirop_id?: number;
    created_at?: string;
    updated_at?: string;
    visite?: Visite;
    sirop?: Sirop;
};
export type Partenaire = {
    id: number;
    nom: string;
    code: string;
    exploitation_id: number;
    created_at?: string;
    updated_at?: string;
    exploitation?: Exploitation;
    ruchers?: Rucher[];
};
export type Pesee = {
    id: number;
    poids: any;
    temperature?: number;
    hygrometrie?: number;
    visite_id: number;
    commentaires?: string;
    created_at?: string;
    updated_at?: string;
    visite?: Visite;
};
export type PoseElement = {
    id: number;
    visite_id: number;
    grille_a_reine: boolean;
    grille_a_propolis: boolean;
    chasse_abeilles: boolean;
    bonnet: boolean;
    chaussette: boolean;
    chaussure: boolean;
    echarpe: boolean;
    coussin: boolean;
    lange: boolean;
    lanieres: boolean;
    trappe_a_pollen: boolean;
    commentaires?: number;
    created_at?: string;
    updated_at?: string;
    visite?: Visite;
};
export type PoseHausses = {
    id: number;
    nb_hausses_posees: number;
    visite_id: number;
    created_at?: string;
    updated_at?: string;
    visite?: Visite;
    hausses?: Hausse[];
};
export type ProduitTraitement = {
    id: number;
    nom: string;
    lanieres: boolean;
    created_at?: string;
    updated_at?: string;
};
export type RecolteGeleeRoyale = {
    id: number;
    visite_id: number;
    qte_gelee_royale: number;
    created_at?: string;
    updated_at?: string;
    visite?: Visite;
};
export type RecolteMiel = {
    id: number;
    miellee_id: number;
    visite_id: number;
    nb_hausses_recoltees: number;
    qte_miel_recolte?: number;
    created_at?: string;
    updated_at?: string;
    miellee?: Miellee;
    visite?: Visite;
    hausses_recoltees?: HausseRecoltee[];
};
export type RecoltePollen = {
    id: number;
    visite_id: number;
    qte_pollen: number;
    created_at?: string;
    updated_at?: string;
    visite?: Visite;
};
export type RecoltePropolis = {
    id: number;
    visite_id: number;
    qte_propolis: string;
    created_at?: string;
    updated_at?: string;
    visite?: Visite;
};
export type Reine = {
    id: number;
    reference: string;
    exploitation_id: number;
    souche_id?: number;
    annee_naissance: number;
    numero_dossard?: string;
    marquee: boolean;
    morte: boolean;
    vendue: boolean;
    donnee: boolean;
    essaimee: boolean;
    generation?: string;
    mere_id?: number;
    pere?: string;
    commentaires?: string;
    created_at?: string;
    updated_at?: string;
    couleur: any;
    exploitation?: Exploitation;
    mere?: Reine;
    souche?: Souche;
};
export type RenouvellementCires = {
    id: number;
    visite_id: number;
    nb_cadres: number;
    commentaires?: string;
    created_at?: string;
    updated_at?: string;
    visite?: Visite;
};
export type Reunion = {
    id: number;
    visite_id: number;
    ruche_destination_id?: number;
    ruche_origine_id?: number;
    reine_origine_id?: number;
    reine_destination_id?: number;
    reine_conservee_id?: number;
    commentaires?: string;
    created_at?: string;
    updated_at?: string;
    visite?: Visite;
    ruche_destination?: Ruche;
    ruche_origine?: Ruche;
    reine_origine?: Reine;
    reine_destination?: Reine;
    reine_conservee?: Reine;
};
export type Role = {
    id: number;
    nom: string;
    is_proprietaire: boolean;
    acces_complet_ruchers: boolean;
    exploitation_id: number;
    peut_creer_ruches: boolean;
    peut_creer_ruchers: boolean;
    peut_creer_taches: boolean;
    peut_modifier_planning: boolean;
    peut_inviter_apiculteurs: boolean;
    peut_modifier_exploitation: boolean;
    peut_exporter_documents: boolean;
    peut_gerer_roles: boolean;
    created_at?: string;
    updated_at?: string;
    exploitation?: Exploitation;
    ruchers?: Rucher[];
    users?: User[];
};
export type Ruche = {
    id: number;
    reference: string;
    vide: boolean;
    note: number;
    qr_code: string;
    gestion_rbc: boolean;
    archivee: boolean;
    souche_id?: number;
    rucher_id?: number;
    reine_id?: number;
    type_ruche_id: number;
    exploitation_id: number;
    created_at?: string;
    updated_at?: string;
    rucher?: Rucher;
    exploitation?: Exploitation;
    todos?: Todo[];
    hausses?: Hausse[];
    visites?: Visite[];
    nourrissements?: Nourrissement[];
    notes?: Note[];
    souche?: Souche;
    reine?: Reine;
};
export type Rucher = {
    id: number;
    nom: string;
    exploitation_id: number;
    latitude?: any;
    longitude?: any;
    environnement?: string;
    adresse1?: string;
    adresse2?: string;
    code_postal?: string;
    ville?: string;
    pays?: string;
    created_at?: string;
    updated_at?: string;
    exploitation?: Exploitation;
    roles?: Role[];
    partenaires?: Partenaire[];
    ruches?: Ruche[];
    todos?: Todo[];
    notes?: Note[];
};
export type Sirop = {
    id: number;
    nom: string;
    pourcentage_sucre: number;
    exploitation_id: number;
    created_at?: string;
    updated_at?: string;
    nourrissements?: Nourrissement[];
    exploitation?: Exploitation;
};
export type Souche = {
    id: number;
    nom: string;
    exploitation_id: number;
    created_at?: string;
    updated_at?: string;
    exploitation?: Exploitation;
    ruches?: Ruche[];
    reines?: Reine[];
};
export type Todo = {
    id: number;
    titre: string;
    description?: string;
    rucher_id?: number;
    ruche_id?: number;
    exploitation_id: number;
    date?: string;
    date_notification?: string;
    notif_envoyee: boolean;
    fait: boolean;
    created_at?: string;
    updated_at?: string;
    rucher?: Rucher;
    ruche?: Ruche;
    exploitation?: Exploitation;
};
export type Traitement = {
    id: number;
    notes: string;
    autres_traitements: string;
    produit_traitement_id: number;
    visite_id: number;
    created_at?: string;
    updated_at?: string;
    produit_traitement?: ProduitTraitement;
    visite?: Visite;
};
export type Transvasement = {
    id: number;
    visite_id: number;
    ruche_destination_id?: number;
    ruche_origine_id?: number;
    commentaires?: number;
    created_at?: string;
    updated_at?: string;
    visite?: Visite;
    ruche_destination?: Ruche;
    ruche_origine?: Ruche;
};
export type TypeCadre = {
    id: number;
    nom: string;
    est_divisible: boolean;
    initiales: string;
    created_at?: string;
    updated_at?: string;
    cadres?: Cadre[];
};
export type TypeRuche = {
    id: number;
    nom: string;
    nb_cadres: number;
    exploitation_id?: number;
    created_at?: string;
    updated_at?: string;
    ruches?: Ruche[];
    exploitation?: Exploitation;
};
export type User = {
    id: number;
    nom?: string;
    prenom: string;
    email: string;
    email_verified_at?: string;
    created_at?: string;
    updated_at?: string;
    current_exploitation_id?: number;
    visites?: Visite[];
    exploitations?: Exploitation[];
    owned_exploitations?: Exploitation[];
    exploitation_roles?: ExploitationUserRole[];
    current_exploitation?: Exploitation;
};
export type Visite = {
    id: number;
    date: string;
    exploitation_id: number;
    auteur_id: number;
    ruche_id: number;
    rucher_id?: number;
    nom?: string;
    created_at?: string;
    updated_at?: string;
    auteur?: User;
    ruche?: Ruche;
    exploitation?: Exploitation;
    nourrissement?: Nourrissement;
    traitement?: Traitement;
    pose_hausses?: PoseHausses;
    recolte_miel?: RecolteMiel;
    recolte_propolis?: RecoltePropolis;
    recolte_pollen?: RecoltePollen;
    recolte_gelee_royale?: RecolteGeleeRoyale;
    pesee?: Pesee;
    mort?: Mort;
    comptage?: Comptage;
    controle?: Controle;
    nettoyage_plancher?: NettoyagePlancher;
    renouvellement_cire?: RenouvellementCires;
    apiculteurs?: User[];
    division?: Division;
    pose_elements?: PoseElement;
    transvasement?: Transvasement;
    reunion?: Reunion;
    introduction?: Introduction;
};
